# Generated by Django 2.1.5 on 2019-03-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('delivered', 'Delivered')], default='created', max_length=100)),
                ('shipment_total', models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.Cart')),
            ],
        ),
    ]
