# Generated by Django 2.1.5 on 2019-03-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190318_1350'),
        ('billing', '0003_remove_billingprofile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.GuestEmail'),
        ),
    ]
